### ISSUE TITLE
fn is not a function

### ISSUE THREAD

**Issue by cah-brian-gantzler** [pzuraq/ember-decorators-polyfill#10]
I have a new addon, one component, just started, barely anything there. I have installed ember-cli-addon-docs and created a demo of this simple component, basically its rendering an input.

Since I want to attach some actions up, and I want to use the new decorators, I included this addon. I have not imported or used anything, just included the addon, and I now get an error when trying to run the demo app. The error is in the following code

error is: Uncaught (in promise) TypeError: fn is not a function

```
 function buildComputedDesc(dec, prototype, key, desc) {
    let fn = DECORATOR_COMPUTED_FN.get(dec);
    let params = DECORATOR_PARAMS.get(dec);
    let modifiers = DECORATOR_MODIFIERS.get(dec);
    let computedDesc = fn(prototype, key, desc, params);
    (true && !(isComputedDescriptor(computedDesc)) && Ember.assert("computed decorators must return an instance of an Ember ComputedProperty descriptor, received ".concat(computedDesc), isComputedDescriptor(computedDesc)));

    if (modifiers) {
      modifiers.forEach(m => {
        if (Array.isArray(m)) {
          computedDesc[m[0]](...m[1]);
        } else {
          computedDesc[m]();
        }
      });
    }

    return computedDesc;
  }
```

on line 
```
let computedDesc = fn(prototype, key, desc, params);
```

**Comment by pzuraq** [comment]
This is likely because of the version of `ember-concurrency` that `ember-cli-addon-docs` was using. Can you try updating ec-addon-docs to the latest version?

**Comment by lupestro** [comment]
Another experience of this, in case somebody else stumbles in here. I've just run into it in an app - I removed `ember-decorators`, put in `ember-decorators-polyfill`, and rewired the one class where I was using `@computed` to get it from `@ember/object` instead of `@ember-decorators/object`. The only thing using `ember-concurrency` in my app is `ember-power-select`, and it looks like the version I was using has picked up 0.8.26, not 0.9.0, which was the root of the problem in my case. Updating `ember-power-select` from 2.2.2 to 2.3.1 solved the problem for me.

**Comment by cah-brian-gantzler** [comment]
Upgrading to ember-cli-addon-docs 0.6.10 I believe fixed this issue
