### ISSUE TITLE
Seems to break ember-concurrency, or anything extending from ComputedProperty

### ISSUE THREAD

**Issue by peabnuts123** [pzuraq/ember-decorators-polyfill#17]
Howdy all. I was just trying out this addon in my project yesterday, and I faced the same issue as #10. I'm creating a new issue, because 10 was closed, but the underlying issue was not resolved, it was just worked-around by people upgrading their dependencies.

It seems there is an assumption made in this addon about the usage of Ember computed properties (i.e. `import { computed } from '@ember/object';`), that they will ALWAYS be decorators. This breaks compatibility with certain addons as well as the standard Ember library. For example, `ember-concurrency`'s Task object extends from `ComputedProperty`, to be used as such:

```js
  myTask: task(function* (){ 
    …
  }),
```

much like a computed property. However, this addon overrides the `ComputedProperty` class to make it extend from `DecoratorDescriptor` which means the logic parsing this code now treats the above ember-concurrency code as a decorator, which throws the error `TypeError: fn is not a function` (it returns an object, not a function). Similarly, with decorators landing in Ember 3.10, developers can still use `computed()` in the traditional sense, without using it as a Decorator, which it seems like this addon may break. 

Am I correct in my understanding here? Is there something that can be done to mitigate this? I can't use this addon, as I'm going to have to wait until I make it to Ember 3.10 to upgrade `ember-decorators` to version 6.

**Comment by pzuraq** [comment]
This is not the assumption this addon makes, it does hack into the ComputedProperty system, but it does so in a way that should allow decorators to work in both classic classes and as native decorators. We have [tests covering both use cases](https://github.com/pzuraq/ember-decorators-polyfill/blob/master/tests/unit/computed-test.js#L131). Using this addon should be API compatible with Ember 3.10.

Extending the `ComputedProperty` class is something we actually broke upstream in Ember 3.10 as well, which is why a few addons started having failures. Extending was never public API, but a few Ember experts hacked into the system to get things to work. We worked directly with those addons (mainly `ember-concurrency`) to update their systems to work with the new decorators system in Ember 3.10, and with the polyfill shipped here. Since `ember-concurrency` was using private APIs that _had_ to break in order to ship this feature, the only solution for users of the library is to upgrade the library.

Are you having problems with a specific library? I can try to help out of provide guidance if so, can you provide more details?

**Comment by BryanCrotaz** [comment]
> Since ember-concurrency was using private APIs that had to break in order to ship this feature, the only solution for users of the library is to upgrade the library

To which version?

**Comment by pzuraq** [comment]
v0.9.0+ should be sufficient, the fix was merged before then

**Comment by pzuraq** [comment]
I'm going to close this issue for now, let me know if you're still having problems after upgrading!
